[tool.poetry]
name = "maths"
version = "0.1.0"
description = ""
authors = ["Samir Seth <samir@sarvam.ai>"]
readme = "README.md"
packages = [{include = "maths"}]

[tool.poetry.dependencies]
python = "^3.13"
sympy = "^1.13"
numpy = "^2.1"
matplotlib = "^3.9"
plotly = "^5.24"
astropy = "^6.1"
pandas = "^3.0.5"
jinja2 = "^3.1.6"
scipy = "^1.18.0"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29"
jupytext = "^1.19.5"
ipywidgets = "^8.1.8"


[tool.jupytext]
formats = "ipynb,py:percent"

[tool.mypy]
plugins = "numpy.typing.mypy_plugin"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
